angular.module('Admission.videoIntro',[])
.controller('VideoController',function($scope,$window,$location,VideoIntro){
	$scope.videoLink={};
	$scope.sendVideoLink=function(){
		$scope.videoLink.id=$window.localStoarge.getItem('user');
		VideoIntro.sendVideoLink($scope.videoLink)
		.then(function(resp){
			console.log(resp);
		})
	}
})